"""GitHub issue -> agent run -> branch -> commit -> (push) -> (draft PR).

Trust boundary: AgentForge (trusted) clones and pushes using the GitHub token;
the agent works on the clone inside its sandbox and never receives the token.
Pushing and opening a pull request are explicit opt-ins, the pull request is
always a draft, and nothing is ever merged - a human reviews every change.
"""

from __future__ import annotations

import base64
import logging
import os
import re
from dataclasses import dataclass, field
from pathlib import Path

from agentforge.core.config import AgentConfig
from agentforge.core.errors import AgentForgeError
from agentforge.core.models import Run, RunStatus
from agentforge.evaluation.base import EvaluatorSpec
from agentforge.integrations.github.client import GitHubClient, Issue, parse_repo
from agentforge.memory.base import MemoryStore
from agentforge.observability.redaction import Redactor
from agentforge.runtime.events import RunObserver
from agentforge.runtime.factory import prepare_run
from agentforge.sandbox.base import ExecResult
from agentforge.sandbox.local import run_process
from agentforge.settings import Settings

logger = logging.getLogger("agentforge.github")

AGENT_IDENTITY = ("AgentForge Agent", "agent@agentforge.invalid")

ISSUE_PROMPT = """Resolve this GitHub issue in the repository checked out in your workspace.

Repository: {repo}
Issue #{number}: {title}
URL: {url}
Labels: {labels}

{body}
{comments}
Instructions:
- Explore the repository to understand the relevant code before changing it.
- Make a focused change that resolves the issue; add or update tests when appropriate.
{test_hint}- Commit your work with git (a clear message referencing #{number}).
- Do not push or open pull requests; a human will review your commit.
- Finish with a summary of the change and how you verified it."""


class GitHubWorkflowError(AgentForgeError):
    code = "github_workflow_error"


@dataclass
class IssueTaskRequest:
    repo: str
    issue_number: int
    config: AgentConfig
    base_branch: str | None = None
    test_command: str | None = None
    push: bool = False
    open_pr: bool = False
    allow_failing: bool = False
    agent_id: str | None = None
    remote_url: str | None = None  # override clone/push URL (mirrors, tests)


@dataclass
class IssueTaskResult:
    run: Run
    issue: Issue
    branch: str
    base_branch: str
    commits: int
    pushed: bool = False
    pr_url: str | None = None
    notes: list[str] = field(default_factory=list)


def branch_name(issue: Issue) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", issue.title.lower()).strip("-")[:40].strip("-")
    return f"agentforge/issue-{issue.number}" + (f"-{slug}" if slug else "")


def build_goal(repo: str, issue: Issue, comments: list[str], test_command: str | None) -> str:
    comment_text = ""
    if comments:
        comment_text = "\nDiscussion:\n" + "\n---\n".join(c[:2_000] for c in comments[:20]) + "\n"
    test_hint = (
        f"- Verify your change by running `{test_command}` until it passes.\n"
        if test_command
        else "- Run the project's tests if it has any.\n"
    )
    return ISSUE_PROMPT.format(
        repo=repo,
        number=issue.number,
        title=issue.title,
        url=issue.html_url,
        labels=", ".join(issue.labels) or "-",
        body=(issue.body or "(no description)")[:20_000],
        comments=comment_text,
        test_hint=test_hint,
    )


def pr_body(result: IssueTaskResult) -> str:
    run = result.run
    lines = [
        f"Automated change for #{result.issue.number} generated by an AgentForge agent.",
        "",
        "**This pull request requires human review. AgentForge never merges changes.**",
        "",
        f"- Run: `{run.id}` ({run.status.value})",
        f"- Agent: `{run.agent_name}` using `{run.config.model.provider}/{run.config.model.model}`",
        f"- Steps: {run.metrics.steps}, tool calls: {run.metrics.tool_calls}",
    ]
    if run.evaluation is not None:
        lines.append(
            f"- Evaluation: {'passed' if run.evaluation.passed else 'FAILED'} "
            f"(score {run.evaluation.score})"
        )
        lines += [f"  - {'✅' if r.passed else '❌'} {r.name}" for r in run.evaluation.results]
    if run.result:
        lines += ["", "### Agent summary", "", run.result[:5_000]]
    lines += ["", f"Closes #{result.issue.number}"]
    return "\n".join(lines)


class GitRunner:
    """Runs git on the host for trusted operations (clone, push)."""

    def __init__(self, token: str | None, redactor: Redactor) -> None:
        self._token = token
        self._redactor = redactor
        redactor.add_secret(token)
        if token:
            basic = base64.b64encode(f"x-access-token:{token}".encode()).decode()
            redactor.add_secret(basic)
            self._auth = ["-c", f"http.extraHeader=Authorization: Basic {basic}"]
        else:
            self._auth = []

    async def __call__(
        self, *args: str, cwd: Path, auth: bool = False, timeout: float = 600
    ) -> ExecResult:
        env = {
            k: v
            for k, v in os.environ.items()
            if k
            in (
                "PATH",
                "HOME",
                "LANG",
                "SSL_CERT_FILE",
                "GIT_SSL_CAINFO",
                "HTTPS_PROXY",
                "HTTP_PROXY",
                "NO_PROXY",
            )
        }
        env["GIT_TERMINAL_PROMPT"] = "0"
        argv = ["git", *(self._auth if auth else []), *args]
        result = await run_process(
            argv, cwd=str(cwd), env=env, timeout=timeout, stdin=None, output_limit=64_000
        )
        if not result.ok:
            stderr = self._redactor.redact_text(result.stderr.strip())[:1_000]
            raise GitHubWorkflowError(f"git {args[0]} failed: {stderr}")
        return result


async def _checkout(git: GitRunner, remote: str, base: str, branch: str, workspace: Path) -> None:
    await git(
        "clone",
        "--quiet",
        "--branch",
        base,
        remote,
        str(workspace),
        cwd=workspace.parent,
        auth=True,
    )
    await git("config", "user.name", AGENT_IDENTITY[0], cwd=workspace)
    await git("config", "user.email", AGENT_IDENTITY[1], cwd=workspace)
    await git("switch", "-c", branch, cwd=workspace)


async def solve_issue(
    request: IssueTaskRequest,
    *,
    settings: Settings,
    client: GitHubClient,
    token: str | None,
    observers: list[RunObserver] | None = None,
    memory: MemoryStore | None = None,
    env: dict[str, str] | None = None,
    run: Run | None = None,
) -> IssueTaskResult:
    """Execute the workflow. Pass ``run`` to fill in a pre-created (pending) run record."""
    if request.open_pr and not request.push:
        raise GitHubWorkflowError("opening a pull request requires pushing the branch (--push)")
    owner, name = parse_repo(request.repo)
    redactor = Redactor.from_environment(env)
    git = GitRunner(token, redactor)

    issue = await client.get_issue(request.repo, request.issue_number)
    if issue.is_pull_request:
        raise GitHubWorkflowError(f"#{issue.number} is a pull request, not an issue")
    comments = await client.list_issue_comments(request.repo, request.issue_number)
    repo_info = await client.get_repository(request.repo)
    base = request.base_branch or str(repo_info.get("default_branch") or "main")
    branch = branch_name(issue)
    remote = request.remote_url or f"https://github.com/{owner}/{name}.git"

    # The prepared run owns the workspace directory; clone into it.
    evaluators: list[EvaluatorSpec] = [
        EvaluatorSpec(
            type="command",
            name="has_commits",
            command=f"test $(git rev-list --count origin/{base}..HEAD) -gt 0",
        )
    ]
    if request.test_command:
        evaluators.insert(
            0, EvaluatorSpec(type="command", name="tests", command=request.test_command)
        )
    goal = build_goal(request.repo, issue, comments, request.test_command)
    labels = {"github_repo": request.repo, "github_issue": str(issue.number), "branch": branch}
    if run is not None:
        run.goal = goal
        run.labels.update(labels)
    prepared = prepare_run(
        request.config,
        goal,
        agent_id=request.agent_id,
        settings=settings,
        memory=memory,
        observers=observers,
        env=env,
        labels=labels,
        run=run,
    )
    workspace = prepared.runtime.deps.workspace.root
    try:
        await _checkout(git, remote, base, branch, workspace)
    except BaseException:
        await prepared.provider.aclose()
        raise

    run = await prepared.execute(evaluators)
    result = IssueTaskResult(run=run, issue=issue, branch=branch, base_branch=base, commits=0)

    status = await git("status", "--porcelain", cwd=workspace)
    if status.stdout.strip():
        await git("add", "--all", cwd=workspace)
        await git(
            "commit",
            "--quiet",
            "-m",
            f"AgentForge: uncommitted changes for #{issue.number}",
            cwd=workspace,
        )
        result.notes.append("the agent left uncommitted changes; they were committed for review")
    count = await git("rev-list", "--count", f"origin/{base}..HEAD", cwd=workspace)
    result.commits = int(count.stdout.strip() or 0)

    succeeded = run.status == RunStatus.SUCCEEDED and (
        run.evaluation is None or run.evaluation.passed
    )
    if not request.push:
        result.notes.append(f"branch {branch} left in the local workspace (push not requested)")
        return result
    if result.commits == 0:
        result.notes.append("nothing to push: the agent made no commits")
        return result
    if not succeeded and not request.allow_failing:
        result.notes.append("not pushing: the run or its evaluation failed (use --allow-failing)")
        return result

    await git("push", "--quiet", remote, f"HEAD:refs/heads/{branch}", cwd=workspace, auth=True)
    result.pushed = True
    if request.open_pr:
        pr = await client.create_pull_request(
            request.repo,
            title=f"[AgentForge] {issue.title} (#{issue.number})"[:250],
            head=branch,
            base=base,
            body=pr_body(result),
            draft=True,
        )
        result.pr_url = pr.html_url
    return result
